### ISSUE TITLE
Monitor Application health

### ISSUE THREAD

**Issue by nehmebilal** [Microsoft/Yams#11]
When an application is deployed, each Yams instance downloads the application from storage and start a process using the provided exe. Yams then assumes that the process has started correctly and moves on to the next app.

It would be great if Yams can make sure that the app has started correctly. It would be also great if the current behavior is preserved if the app itself has no support for health checks to make sure that we can still run any exe in Yams. We still need to define how Yams and the app will communicate.

In particular, during an upgrade of an application, Yams should rollback to the previous working version if the new version fails to start. Yams should not move to the next fault / upgrade domain until the current one has been successfully upgraded (or rolled back).

Thanks to @ReubenBond for the suggestion.

**Comment by remusrg** [comment]
If my understanding is correct, between Application and ApplicationPool this is handled currently via the Exited event. If the application process cannot start and throws an exception right away, Yams will keep on trying. If the application process does start but dies right away, Yams will handle that by removing the application from the pool, which in turn will cause the application to be restarted again, up to a certain number of times. If this is correct, does that not satisfy the requirements?

**Comment by nehmebilal** [comment]
I'll have to take a closer look but I'm pretty sure that if the application fails to start, Yams will simply log the error and continue with the next app.

As a result, in an attempt to update from 1.0 to 2.0, we could very well take down all instance of 1.0 and fail to start 2.0 (if 2.0 is broken). VM 2 should not start the update until VM 1 is done. VM 1 is done means that it successufly performed the update or rolled back to the original working version.

**Comment by remusrg** [comment]
You could theoretically not remove the stable previous version until such time when an acceptance test against the new version has been executed successfully. It would involve a two step commit to the new version but it might alleviate the concern of tearing down a working version before we knew the new one is stable. We've always highlighted the fact that the applications running on YAMS are assumed to be designed in a way that allows side by side execution across versions... Yes, depending on the design of the app this might take a data migration step. Thoughts?

**Comment by ReubenBond** [comment]
> You could theoretically not remove the stable previous version until such time when an acceptance test against the new version has been executed successfully.

@remusrg that's the behavior I was after, particularly not moving onto the next fault domain / upgrade domain until the current one has been *successfully* upgraded.

**Comment by remusrg** [comment]
If the scope is update domain only and not smaller than that I think we already do that. Smaller than the update domain would create issues with ports, etc. Sounds like we need an optional probe API/Uri that is declared via the app/deployment configuration that YAMS can hit though in order to check for availability.

**Comment by nehmebilal** [comment]
> @remusrg We've always highlighted the fact that the applications running on YAMS are assumed to be designed in a way that allows side by side execution across versions

Running side by side is not a requirement in Yams. The application must be designed that way *only if* it's meant to run multiple versions side by side, otherwise, developers shouldn't need to worry about that aspect.

**Comment by nehmebilal** [comment]
> @ReubenBond that's the behavior I was after, particularly not moving onto the next fault domain / upgrade domain until the current one has been *successfully* upgraded.

*Successfully upgraded* or reverted to the previous working version. Otherwise we can't move to the next app.

**Comment by nehmebilal** [comment]
By the way, there was an assumption that binaries are first tested in a staging cluster before deploying to production. Because it's the same binaries, there is little chance that the app will fail to start in production if it successfully worked in staging. However, it can happen and it would be better if Yams handles the rollback.

**Comment by nehmebilal** [comment]
I updated the description based on comments.

**Comment by remusrg** [comment]
:+1:

**Comment by nehmebilal** [comment]
After some investigation, the rollback behavior is a bit problematic. In fact, Yams is currently controlled by the `DeploymentConfig.json` file that resides in the deployment repository. Yams only reads from that file but never writes to it. The `DeploymentConfig.json` is usually controlled by an external actor (e.g. human, CI, etc). 

If we implement a rollback, Yams will have to update the `DeploymentConfig.json` file which is problematic.

I am leaning towards leaving the rollback part outside of Yams. Maybe the following?

* We use a second json file that represents the status of the deployments in the Yams cluster(s). This file, let's call it `DeploymentStatus.json` is what external actors use to determine the status of the cluster (what application/version is currently running on what cluster and VM). It's basically a feedback from Yams to the outside world.
* If an application fails to update, the failure is marked in the `DeploymentStatus.json` file and it's up to the external actor to decide if they wish to revert (by modifying the `DeploymentConfig.json`) file, not do anything (which means Yams will retry at the next iteration) or to fix the application and deploy a new version.
* If an application update fails on one upgrade domain, Yams will not attempt to perform the update on the next upgrade domain until the situation has been resolved (i.e. retry succeeded or a new version is being deployed).

Thoughts?

**Comment by ReubenBond** [comment]
Sounds good to me, @nehmebilal! That limits the damage of a bad version and lets developers fix it by simply pushing a new version.

**Comment by nehmebilal** [comment]
Yes exactly!

Also the `DeploymentStatus.json` will make it possible to provide feedback to developers that is a lot easier to read than logs :) It'll basically make Yams observable.

**Comment by danvanderboom** [comment]
@nehmebilal A failed-health app could remain in the deployment definition, but it could have a status indicating "not currently installed/running due to health failure". A .json config file may not be the best way to expose app status. Some kind of service call to get the current list of healthy running applications (or apps whose health is unreported), or to check if a given app is running in a healthy (or unknown state), would be good through the API, similar to the way the storage API provides a nice interface to the Yams library.

**Comment by nehmebilal** [comment]
@danvanderboom Yes, the API would look similar to the storage API but can still be backed by blob storage (if that's simpler than a web API). As you mentioned on Gitter, the API would also allow apps to report their status (periodically) which sounds like a simpler solution that inter-process communication between the Yams cluster and the apps. We can provide all the boiler plate code so that apps developers don't to do much to get reporting wired.

**Comment by nehmebilal** [comment]
I played with anonymous/named pipes for IPC and it seems like a good way to communicate between Yams and the hosted services (on the same machine).

**Comment by nehmebilal** [comment]
This has been partially solved in #37. 

I'll keep it open since there are some bits that have not been addressed (worth summarizing when I or someone get a chance).
