### ISSUE TITLE
Support prerelease versions like in SemVer

### ISSUE THREAD

**Issue by aprooks** [Microsoft/Yams#30]
I would like to be able to deploy prerelease versions of an app, that have same version part and some suffix, like:

* 0.9.0-feature1
* 0.9.0-feature2
* 0.9.0-bugfix

**Comment by nehmebilal** [comment]
What's the advantage over incrementing the build version? 

I guess if you are testing multiple features (or bug fixes) that are unrelated, 0.9.0-feature1 and 0.9.0-feature2 is simpler than 0.9.1 and 0.9.2 and makes more sense because 0.9.2 doesn't actually contain the changes in 0.9.1. Is that part of the motivation for this versioning scheme?

**Comment by aprooks** [comment]
Yes you are right. This way we can do several internal version and publish only a single release later. We also have custom policies based on a way package is version. E.g. pre release package is automatically deployed to dev server on nuget publish and just cannot be pushed to production under any circumstances

**Comment by nehmebilal** [comment]
I see. One solution is to make Yams treat the version as a string and only parse it to a `Version` when needed. This way, users can use any versioning scheme they like.

**Comment by remusrg** [comment]
Perhaps a good idea to adopt semantic versioning support? http://semver.org.

		_____________________________

**Comment by aprooks** [comment]
I am voting for SemVer versioning as well.

What do you think about using 3rd party libs like https://github.com/xyncro/semver.net to parse versions?

**Comment by remusrg** [comment]
LGTM and that shouldn't be a problem, I like that it has a nuget package too. We should give it a whirl.

**Comment by nehmebilal** [comment]
Resolved by #32

**Comment by remusrg** [comment]
That's awesome and thank you! We should also update the documentation to reference semantic versioning and give people an example use case of using it.

**Comment by aprooks** [comment]
I will try to blog post the process we achieved once I have some free time
