### ISSUE TITLE
Make DeploymentConfig serializable to JSON

### ISSUE THREAD

**Issue by danvanderboom** [Microsoft/Yams#31]
It would be great if this kind of JSON serialization could work with DeploymentConfig and its supporting types.

var json = JsonConvert.SerializeObject(deploymentConfig);

**Comment by nehmebilal** [comment]
`var json = deploymentConfig.RawData();` should work.

**Comment by danvanderboom** [comment]
How about going in the other direction? That gets a serialized form of the current configuration, but I'd like to set it as well from JSON.

I did write a pair of extension methods that convert between DeploymentConfig in YAMS (using RawData for one direction) and a Serializable-friendly version of those types (same type names, different namespace, long qualified type names in those extension methods). By serializable friendly, I mean has a public default constructor, can be serialized or deserialized with standard Newtonsoft or <insert-your-favorite-lib-here> library.

**Comment by nehmebilal** [comment]
There is a constructor in DeploymentConfig that takes the rawdata.

If users only use these Apis to save/load the json, we can change to other formats and users won't even notice. For this reason, we prefer this approach over JsonConvert.

For instance, the Azure deployment repository we have is not aware that rawdata is json.

**Comment by danvanderboom** [comment]
Okay, thanks for the tip! I didn't notice that constructor.

**Comment by nehmebilal** [comment]
No problem :) Resolved?

**Comment by danvanderboom** [comment]
Yeah, it was already working already so I've left it so far, I just did a little extra work to get there. :) At some point, I'll go back and clean it up.
