### ISSUE TITLE
refactoring the YAMS model: from deployments to clusters and node roles

### ISSUE THREAD

**Issue by danvanderboom** [Microsoft/Yams#33]
I think it'd be worth thinking about separating the Deployment (and DeploymentId) abstraction into separate abstractions for Cluster and NodeType (or role), making both of these ideas first-class citizens in the YAMS model.

Within a cluster, we sometimes want to designate different node types, installing different collections of services and apps on each type of node. But we also want to make sure we don't mix up deployments to different clusters/environments, keeping their definitions completely separate. I don't ever want one role in a cluster to affect software configuration on other clusters (accidentally or intentionally). If a second cluster has nodes with the same roles as nodes in another environment, it should be considered separate when any changes are rolled out. Running a tool to update cluster configurations should only affect components on one cluster at a time.

When fetching deployment configuration, a node would say "I belong to cluster x, and I'm node type y", and would then receive the appropriate deployment configuration object.

It's easy enough to fake this now, with the current state of YAMS, creating a single DeploymentId out of two parts like: "QAT-StorageNode", "QAT-ComputeNode", "Prod-StorageNode", "Prod-ComputeNode", etc. But it'd be nice for YAMS to recognize this reality with first-class recognition of both concepts, which are currently combined into a single "deployment" concept.

![Proposed Model]
(https://files.gitter.im/Microsoft/Yams/Rfah/thumb/blob.png)

A current YAMS "deployment" would in this new model consist of all the AppPackageInstalls within a specified NodeType.

When I put my IT admin hat on, I want to see all the clusters, which node types are configured for each environment, and which packages are configured to run on each type of node.

With the right storage abstractions, that becomes much easier. A GUI tool with a TreeView could break down these three levels, let users expand a cluster environment node to see node types, expand those to see packages, drag packages into a node type for a particular cluster to add a reference to the package, etc.

I also imagine AppPackageInstalls having columns for ConfigFilesPackage, which would be just another .zip file (in our implementation) whose contents are unzipped into the app version directory with the rest of the app binaries. This would decouple file-based config (which is still very common and sometimes not within our control) from application binaries deployment, which is great because currently we'd need to publish a different "version" of the app package for it to be recognized with its updated config file. This is a waste of app packages (and deployment storage / disk space), which otherwise could have their versioned packages reused across several/many cluster environments, each with their own dynamic config.

Going along with ConfigFilesPackage, I want to add another property/column for CommandLineArguments (or ExecutionArguments), which would be a string of constant values and token expressions, to be replaced with values by YAMS when it executes the app/service.

Both would be optional.

@nehmebilal mentioned using some kind of extended properties dictionary or property bag to store things like ExecutionArguments, or other platform- or solution-specific parameters.

With this design, both cluster/node configurations and app/service packages could still be immutable. But in separating binaries from config, or providing an optional "config overlay of files", the packages of binaries can be reused across cluster environments, each with their own config files and/or command-line arguments.

Changes to IDeploymentRepository:
```csharp
Task<ClusterConfig> FetchClusterConfig(string clusterId)
Task<NodeTypeConfig> FetchNodeTypeConfig(string clusterId, string nodeTypeId)
Task PublishClusterConfig(ClusterConfig clusterConfig)
Task PublishNodeTypeConfig(NodeTypeConfig nodeTypeConfig)
Task<bool> HasApplicationConfigFiles(AppIdentity appIdentity)
```

Downloading of application config files, if any exist, can be done within the implementation of ```IDeploymentRepository.DownloadApplicationBinaries```, and a ```HasApplicationConfigFiles``` function isn't needed if that data is returned from within NodeTypeConfig.

ClusterConfig would be the ID plus a collection of NodeTypeConfig objects.

I think what I'm proposing is pretty generic. If many YAMS clusters out there will have only a single node type, that's fine. It can by default have a single node type, and all config actions naturally go against that. Once a second node type has been defined/created for a cluster, commands can be more specific about which node type they're assigning app packages to.

A NodeType is simply: a collection of versioned software packages to be installed on the same machine (virtual or otherwise).

AppInstallSetForNode would be a more descriptive name than NodeType, but is otherwise completely awful.

Thoughts?

**Comment by nehmebilal** [comment]
There are several ideas here but I'm going to focus on the `NodeType` proposal to keep the discussion focussed. If I understand correctly, @danvanderboom is proposing adding a `NodeType` (let's call it that for now) field to the DeploymentConfig.json as follows:

```
{
    "Applications":
    [
        {
            "Id": "app1",
            "Version": "1.0.0",
            "DeploymentIds": [ "YAMS_CLUSTER_ID" ],
            "NodeType": "PROD"
        },  
        {
            "Id": "app1",
            "Version": "1.0.1",
            "DeploymentIds": [ "YAMS_CLUSTER_ID"]
            "NodeType": "QA"
        },
    ]
}
```
The Yams host on each node will know its type and will pull the appropriate deployments based on their types as described in the json above.

The current solution is to concatenate PROD or QA to the DeploymentId (which should be renamed to YamsClusterId).

@danvanderboom Is that accurate?

**Comment by danvanderboom** [comment]
Here's how I see it looking, ideally, for a system with three node types in a QA cluster, and where each node type has two services configured to be installed.

```json
{
  "ClusterId": "MyProduct-QA",
  "NodeTypes": [
    {
      "NodeTypeId": "Storage",
      "Services": [
        {
          "Id": "StorageService",
          "Version": "3.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>",
          "Properties": [
            { "ConfigFilesPackageUrl": "<URL to download config files package>" },
            { "AnotherCustomProperty": "..." }
          ]
        },
        {
          "Id": "LoggingService",
          "Version": "1.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>"
        }
      ],
      "Properties": [
        { "FirstService": { "Id": "LoggingService", "Version": "1.0.0.0" } }
      ]
    },
    {
      "NodeTypeId": "ComputeA",
      "Services": [
        {
          "Id": "ComputeServiceA",
          "Version": "3.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>"
        },
        {
          "Id": "LoggingService",
          "Version": "1.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>"
        }
      ]
    },
    {
      "NodeTypeId": "ComputeB",
      "Services": [
        {
          "Id": "ComputeServiceB",
          "Version": "1.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>"
        },
        {
          "Id": "LoggingService",
          "Version": "1.0.0.0",
          "Executable": "<path to .exe>",
          "ExecutableArgs": "<arguments with tokens for special values>"
        }
      ]
    }
  ]
}
```

Then you'd keep separate configurations for the other environments. In my case where I'm storing these in SQL Server, each cluster's config/manifest is a separate row in a table.

**Comment by danvanderboom** [comment]
So when YAMS starts up, it would need to know two things:
1. ClusterId
2. NodeTypeId

**Comment by danvanderboom** [comment]
This is a cluster manifest. And we'd have separate manifests, one for each cluster/environment.

This can be used in a file based way, versioning with code, differentiating its details by solution configuration, and loading the .json file to configure YAMS... and it's also friendly for storing as rows in a database table in case you want centralized configuration.

**Comment by danvanderboom** [comment]
With a Properties dictionary at the Cluster level as well, these settings could be made available to YAMS extensions like deployment storage providers. This would centralize and make convenient configuration for any and all YAMS extensions, as well as any switches or settings that may alter the operation of YAMS (not sure if there are any of these).

**Comment by danvanderboom** [comment]
If we could call:
```csharp
IDeploymentRepository.FetchNodeTypeConfig("MyProduct-QA", "ComputeA")
```
... we get back a NodeTypeConfig or NodeTypeManifest object, which would be one of these:

```json
{
  "NodeTypeId": "ComputeA",
  "Services": [
    {
      "Id": "ComputeServiceA",
      "Version": "3.0.0.0",
      "Executable": "<path to .exe>",
      "ExecutableArgs": "<arguments with tokens for special values>"
    },
    {
      "Id": "LoggingService",
      "Version": "1.0.0.0",
      "Executable": "<path to .exe>",
      "ExecutableArgs": "<arguments with tokens for special values>"
    }
  ]
}
```

**Comment by danvanderboom** [comment]
A SQL Server database setup script for supporting this kind of model:
https://gist.github.com/danvanderboom/a584bbf2fbdb4a626bb72912bd4828f5

**Comment by nehmebilal** [comment]
Thanks for the ideas @danvanderboom. I doubt that we will make such major changes in one go. It would be great if we can focus on one issue at a time. You never know, It's possible that there are existing solutions to some of the challenges you're trying to address.

My suggestion would be to identify functionality that is not supported (or can be improved) and open a corresponding focused issue to discuss each. Baby steps :)

**Comment by nehmebilal** [comment]
Just to list some of the issues discussed here:

* I would like to have a `NodeType` in my `DeploymentConfig.json` so that I can separate my deployments per type into different clusters. This feature would also be useful for Orleans where backend and frontend apps are deployed to separate WorkerRole's. I personally think we should generalize this and make it possible to add any number of user meta-data to the DeploymentConfig.json. I have some ideas but I'll go in more details once we have a dedicated issue :)
* I would like to have separate `DeploymentConfig.json` for unrelated apps. This is totally doable today. For the SQL scenario, you can pass to your host exe the key of the row where the corresponding `DeploymentConfig.json` is stored. Then, pass this down to your implementation of `IDeploymentRepository` which will fetch the right data. It's also doable using the default blob storage solution by using separate storage accounts for unrelated apps. By the way, you can even store the json in different format and then populate the `DeploymentConfig` class using the `AddApplication` Apis.

I'm sure there's more between the lines :)

**Comment by jdom** [comment]
All good ideas. I would also agree with @nehmebilal on doing small changes at a time, as it's easier to look at what's possible once we are closer to the goals. 
In my opinion, the node type addition can already enable a lot. If we do that, I would still consider depreciating the DeploymentId name in favor of something like YamsClusterId, to disambiguate with whatever hosting technology Yams runs on. Node type on the other hand doesn't need a Yams prefix in it, as it is a logical name that only applies inside the (Yams) cluster, and it doesn't matter if other hosting technologies reuse the same name

**Comment by danvanderboom** [comment]
Having a ClusterId and NodeTypeId, and no longer use DeploymentId, would by itself be a large enabler of other things. The SQL script I shared would become possible, for example.

The config representations can be done now, in one way or another, and one form can be easily mapped to another. So yeah, it's really that use of Cluster & NodeType abstractions that are the thing to focus on.

**Comment by nehmebilal** [comment]
Here is what I am thinking to make it possible for users to add additional properties such as "NodeType" easily.

The DeploymentConfig.json will look as follows:
```json
{
    "Applications":
    [
        {
            "Id": "app1",
            "Version": "1.0.0",
            "YamsClusters": [ "YAMS_CLUSTER_ID" ],
			"Properties":
			{
				"NodeType": "PROD"
			}
        },  
        {
            "Id": "app1",
            "Version": "1.0.1",
            "YamsClusters": [ "YAMS_CLUSTER_ID"],
			"Properties":
			{
				"NodeType": "QA"
			}
        },
    ]
}
```

Yams will require an implementation of the following interface to match the deployments to clusters:

```csharp
public interface IAppDeploymentMatcher
{
	bool MatchesCurrentCluster(AppDeploymentConfig appDeploymentConfig);
}
```

The default implementation uses the Yams cluster id:

```csharp
public class YamsClusterIdDeploymentMatcher : IAppDeploymentMatcher
{
	private string _yamsClusterId;
	
	public ClusterIdDeploymentMatcher(string yamsClusterId)
	{
			_yamsClusterId = yamsClusterId;
	}
	
	public bool MatchesCurrentCluster(AppDeploymentConfig appDeploymentConfig)
	{
		return appDeploymentConfig.YamsClusterId == _yamsClusterId;
	}
}
```

To support NodeType, the user can supply a custom implementation as follows:

```csharp
public class CustomAppDeploymentMatcher : IAppDeploymentMatcher
{
	...
	
	public bool MatchesCurrentCluster(AppDeploymentConfig appDeploymentConfig)
	{
		if(appDeploymentConfig.YamsClusterId != _yamsClusterId)
		{
			return false;
		}
		
		// Verify that the node type matches
		string nodeType = "";
		if(appDeploymentConfig.Properties.TryGetValue("NodeType", out nodeType))
		{
			return nodeType == _nodeType;
		}
		return false;
	}
}
```

You could even write a matcher that matches on a start date for a scheduled job. Another example would be a matcher that makes a service call to fetch some configs and decide if the app should be deployed or not.

How does that sound?

**Comment by jdom** [comment]
I think that's reasonable. After this we can update the Cloud Services sample to use a node type that matches the worker role name (in addition to the deployment id) if it supports multiple node types.
I assume these values can also be used as tokens in the command line arguments when launching the external application?

**Comment by danvanderboom** [comment]
That will work for me, @nehmebilal. Thanks for taking the time to focus on this!

**Comment by nehmebilal** [comment]
@danvanderboom No problem :) 

@jdom Good point. Yes, we should be able to make the properties available as tokens that can be used in the AppConfig.json.

**Comment by nehmebilal** [comment]
@danvanderboom Please take a look at #34 and let us know if that works for you.

**Comment by danvanderboom** [comment]
Great work!!

**Comment by nehmebilal** [comment]
1.1.0-rc is up!

**Comment by nehmebilal** [comment]
Closing.. Feel free to re-open if you find any issues.
