### ISSUE TITLE
Yams studio can not be running because of the Newtonsoft.Json version binding setting in App.config

### ISSUE THREAD

**Issue by david0718** [Microsoft/Yams#36]
I tried to run the Yams studio, but exception occurred :+1: 
System.Windows.Markup.XamlParseException was unhandled
Message: An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll
Additional information: 

After I move the code in ctor for the main window, then I could see it is the issue of Newtonsoft.Json version conflicts.

Another thing is could you please show where to see the doc on how to use this lib?
And the design for this lib, I am really interested in this project.

Thanks

David

**Comment by nehmebilal** [comment]
Hi @david0718,

Thanks for reporting, I'll take a look.

What documentation are you looking for? Yams itself or YamsStudio?

**Comment by david0718** [comment]
First of all, many thanks for your reply.

I think both of them will be useful for the community or person who like this project.
You konw it took me one whole night to check all the code of yamn core code without any document.
But for simple steps how to use this framework, it seems we need that guide?

How do you think? :)

Thanks and best regards
David

**Comment by nehmebilal** [comment]
@david0718 There are links to the documentation on the main page of this repo (see [README](https://github.com/Microsoft/Yams/blob/master/README.md)).

**Comment by nehmebilal** [comment]
I just fixed the YamsStudio issue, should run without problems now.

**Comment by nehmebilal** [comment]
Closing this issue as I believe this has been resolved. Please let us know if you have any other issues.
