### ISSUE TITLE
Consider creating separate Host and Client NuGet packages

### ISSUE THREAD

**Issue by jkonecki** [Microsoft/Yams#42]
The new advanced client features (monitored deployments, health checks, graceful shutdown) require yams applications to reference YAMS NuGet package to use YAMS client.

Currently YAMS NuGet package contains several dependencies that are not needed by the client, 'polluting' package dependencied of the client application. This also increases the risk of conflicts between versions required by YAMS and the application.

What is more, Client NuGet package will probably evolve slover than the host so it can be versioned separatelly.

I think a separate NuGet packages for Host and Client will minimize the impact on using advanced YAMS  features in individual applications.

**Comment by nehmebilal** [comment]
Hi @jkonecki,

I totally agree and was considering it as soon as I added the Yams client Api but got a bit lazy and postponed it. I'm actually considering three NuGet packages at this point:

* Etg.Yams.Core: Yams without storage providers (independent of Blob storage).
* Etg.Yams: The current ready to go server side package.
* Etg.Yams.Client: The Yams client.

**Comment by nehmebilal** [comment]
Can this wait until the next release that would hopefully include the load balancer feature described in #43 ?

**Comment by jkonecki** [comment]
I see no problem with waiting.

**Comment by nehmebilal** [comment]
Done.

**Comment by jkonecki** [comment]
Finally, the answer to Life, Universe and Everything! But which package do I need to install to find the question? ;-)

**Comment by nehmebilal** [comment]
:) Etg.Yams for deploying Yams and Etg.Yams.Client for apps that use health features.
