### ISSUE TITLE
Add package version to assembly info

### ISSUE THREAD

**Issue by justmara** [Microsoft/Yams#63]
Currently you cannot identify Yams version used to build your app. This is info dll's build with Yams 1.6.1:
![yams-version](https://user-images.githubusercontent.com/4157587/32833746-fbedc0e6-ca10-11e7-9748-6facbba38fb6.png)
Please, make it synchronized with nuget package version :)

**Comment by nehmebilal** [comment]
Hi @justmara,

The relationship between the dlls version and the NuGets versions is not very clear. For instance, both `Etg.Yams` and `Etg.Yams.Client` NuGets depend on `Etg.Yams.Ipc` dll. How do you version `Etg.Yams.Ipc` in this case? Versioning every dll independently (when the dll content changes) can also become a maintenance burden if we have many dlls.

At this point, the `Date modified` property is one way of distinguishing one version of a given dll from another. This date should also be typically related to the date of when the NuGet package was created.

Thoughts?

**Comment by nehmebilal** [comment]
Please reopen if you still feel that it's relevant.
