### ISSUE TITLE
Minimize network traffic during app deployment

### ISSUE THREAD

**Issue by jkonecki** [Microsoft/Yams#66]
YAMS can be smarter when it comes to downloading app binaries. We can make sure that the apps are downloaded once only and even copy files from previous, locally stored version if the file MD5 hash matches.

Reuben's Yams Uploader is a good starting point: 
https://github.com/ReubenBond/YamsDeploy/blob/master/YamsApplicationManager.cs

**Comment by nehmebilal** [comment]
I think #75 resolves this issue but copying files from previous versions was not implemented. Please reopen or create a separate issue if you feel that adding such capability is worth the effort.
