### ISSUE TITLE
Use XUnit for testing

### ISSUE THREAD

**Issue by nehmebilal** [Microsoft/Yams#9]
@galvesribeiro suggested that we move our tests to XUnit which has better support for .Net Core and cross platform development.

@galvesribeiro Also volunteered to make the change :)

Tracking this here.

**Comment by galvesribeiro** [comment]
Will be my pleasure! :)

Just waiting for #8 get merged to  start...

**Comment by galvesribeiro** [comment]
Ok, now #8 is merged. Will start the port of all tests to xunit later night. More news on this issue soon. ;)
